# Generated by Django 3.2 on 2024-01-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('count_view', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auth')),
            ],
        ),
    ]
