# Generated by Django 3.2 on 2024-02-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240123_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitt',
            name='count_view',
        ),
    ]
